# Default profile for the application--START

# The eureka configuration is used for register this micro service with Service Discovery server  
eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 5
    preferIpAddress: true
    #non-secure-port: 0
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registryFetchIntervalSeconds: 5
#The default profile will run this micro service on following port
server:
  port: 8099

#removed kafka producer and consumer
# Default profile for the application--END